version: '3'
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_TUS_HOST=localhost
      - PUBLIC_TUS_PORT=8080
  backend:
    image: tusproject/tusd:latest
    ports:
      - "8080:8080"